# Generated by Django 2.1.2 on 2018-10-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=200)),
                ('last_move', models.DateTimeField(verbose_name='Dernier mouvement sur le compte')),
                ('baton', models.IntegerField(default=0)),
            ],
        ),
    ]
