# Generated by Django 2.1.2 on 2018-10-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, null=True)),
                ('style', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
